createMissingRelatedEntities: true
deleteDependentEntities: true
filterBots: false
resources:
  - kind: member
    selector:
      query: 'true'
      publicEmailVisibility: 'false'
    port:
      entity:
        mappings:
          identifier: .username
          title: .name
          blueprint: '"gitlabGroupMember"'
          properties:
            state: .state
            locked: .locked
            link: .web_url
            email: .email
  - kind: group
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .full_path
          title: .name
          blueprint: '"gitlabGroup"'
          properties:
            url: .web_url
            visibility: .visibility
            description: .description
          relations:
            members: '[.__members[].username]'
  - kind: project
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .path_with_namespace | gsub(" "; "")
          title: .name
          blueprint: '"service"'
          properties:
            url: .web_url
            readme: file://README.md
            description: .description
            language: .__languages | to_entries | max_by(.value) | .key
          relations:
            group: >-
              .path_with_namespace | gsub(" "; "") | split("/") | .[:-1] |
              join("/")
