createMissingRelatedEntities: true
deleteDependentEntities: true
resources:
  - kind: project
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: .path_with_namespace | gsub(" "; "")
          title: .name
          blueprint: '"service"'
          properties:
            url: .web_url
            readme: file://README.md
            description: .description
            language: .__languages | to_entries | max_by(.value) | .key
  - kind: member
    selector:
      query: 'true'
      publicEmailVisibility: 'false'
      filterBots: 'false'
    port:
      entity:
        mappings:
          identifier: .username
          title: .name
          blueprint: '"member"'
          properties:
            state: .state
            locked: .locked
            link: .web_url
            email: .email
            publicEmail: .__public_email
          relations:
            gitlabGroup: '[.__groups[].full_path]'
            createdBy: .created_by.username
