resources:
  - kind: group
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id | tostring
          title: .name
          blueprint: '"gitlabGroup"'
          properties:
            visibility: .visibility
            url: .web_url
            description: .description
          relations: {}

  - kind: project
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .path_with_namespace | gsub(" "; "")
          title: .name
          blueprint: '"project"'
          properties:
            url: .web_url
            description: .description
            language: .language
            namespace: .namespace
            fullPath: .path_with_namespace
            defaultBranch: .default_branch
          relations:
            group: .namespace.path

  - kind: merge-request
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id | tostring
          title: .title
          blueprint: '"gitlabMergeRequest"'
          properties:
            creator: .author.name
            status: .state
            createdAt: .created_at
            updatedAt: .updated_at
            mergedAt: .merged_at
            link: .web_url
            reviewers: .reviewers | map(.name)
          relations:
            service: '.web_url | split("/") | .[3] + "/" + .[4]'

  - kind: issue
    selector:
      query: 'true'
    port:
      entity:
        mappings:
          identifier: .id | tostring
          title: .title
          blueprint: '"gitlabIssue"'
          properties:
            link: .web_url
            description: .description
            createdAt: .created_at
            updatedAt: .updated_at
            closedAt: .closed_at
            creator: .author.name
            status: .state
            labels: .labels | map(.name)
          relations:
            service: '.web_url | split("/") | .[3] + "/" + .[4]'
